<template>
  <div class="p-3 bg-neutral-700 rounded-lg text-center flex items-center justify-center space-x-2">
    <span class="text-xl">{{ icon }}</span>
    <p class="text-sm font-medium">{{ headline }}</p>
  </div>
</template>

<script setup>
/**
 * @file HeadlineInsight.vue
 * @description
 * A simple component to display a single, high-level "headline" insight
 * generated by the SOA analysis, prefixed with a semantic icon.
 */
import { computed } from 'vue';

const props = defineProps({
  /**
   * The headline text to display.
   * @type {String}
   */
  headline: {
    type: String,
    required: true,
  },
});

/**
 * Determines which icon to display based on keywords in the headline text.
 * @returns {string} The emoji icon.
 */
const icon = computed(() => {
  if (!props.headline) return '📈';

  const negativeKeywords = ['troppo stretti', 'troppo ambizioso', 'pattern psicologico', 'anomalo'];
  const positiveKeywords = ['ben calibrato', 'realistico', 'stabili', 'analisi completata'];

  const lowerHeadline = props.headline.toLowerCase();

  if (negativeKeywords.some(keyword => lowerHeadline.includes(keyword))) {
    return '⚠️';
  }
  if (positiveKeywords.some(keyword => lowerHeadline.includes(keyword))) {
    return '✅';
  }

  return '📈'; // Neutral/opportunity default
});
</script>
