<template>
  <div class="p-3 bg-neutral-700 rounded-lg text-center">
    <p class="text-sm font-medium">{{ headline }}</p>
  </div>
</template>

<script setup>
/**
 * @file HeadlineInsight.vue
 * @description
 * A simple component to display a single, high-level "headline" insight
 * generated by the SOA analysis.
 */

defineProps({
  /**
   * The headline text to display.
   * @type {String}
   */
  headline: {
    type: String,
    required: true,
  },
});
</script>
